### PR TITLE
Handle capitializations of http header, host

### LINKED ISSUE #26: HTTP headers - Server doesn't handle capitalization in header fields.
### Problem

Following your examples I created the Thing which is connected to my network. 

I used both Chrome and the Mozilla Gateway (0.12) to fetch the Thing's description.

Using Chrome, retrieving the Thing via `http://192.168.11.107` returns a 403 error because Chrome sends the headers with `Host` capitalized. 

```
{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'Host': '192.168.11.107', 'Upgrade-Insecure-Requests': '1'}
```

[validateHost](https://github.com/mozilla-iot/webthing-upy/blob/37119c17621ca407ff7d9795963434808cae6165/webthing/server.py#L277) expects `host` and not `Host`. 

Also, using the Gateway Thing lookup can't find this Thing on the network.

### What is expected

The HTTP spec states headers should be handled as case-insensitive. So `host` or `Host` should be acceptable.

http://www.ietf.org/rfc/rfc2616.txt

> 4.2 Message Headers
> 
>    HTTP header fields, which include general-header (section 4.5),
>    request-header (section 5.3), response-header (section 6.2), and
>    entity-header (section 7.1) fields, follow the same generic format as
>    that given in Section 3.1 of RFC 822 [9]. Each header field consists
>    of a name followed by a colon (":") and the field value. Field names
>    are case-insensitive. 

### Work around
There are at least three locations in the code where `httpClient.GetRequestHeaders().get('Host', None)` is used.

`httpClient.GetRequestHeaders()` is a dictionary and a case-insitive lookup on the key is not possible. Also, the headers are defined by [microWebSrv](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/microWebSrv) which are capitalized.

Instead of handling case-insesitivity I think handling capitialization would do. So,,,

`host = headers.get('host', None)` [here](https://github.com/mozilla-iot/webthing-upy/blob/37119c17621ca407ff7d9795963434808cae6165/webthing/server.py#L277)

should become,

`host = headers.get('host', None) or headers.get('Host', None)`

After this change the Thing was found by the Gateway and a 200 response as expected in Chrome.

### Fix
I will submit a PR in the next day or two. Hopefully the work around is suitable.

### PR DESCRIPTION
**Pull request by trentmillar**
closes #26

### CODE REVIEW

**Comment by mrstegeman** [comment]
A helper method might be a bit cleaner:

```python
def get_header(self, headers, key, default):
  standardized = {k.lower(): v for k, v in headers.items()}
  return standardized.get(key, default)
```

Then, you can do this:

```python
self.get_header(httpClient.GetRequestHeaders(), 'host', None)
```

**Comment by trentmillar** [comment]
of course, I'll update to keep it DRY.

**Review by mrstegeman — CHANGES_REQUESTED** [review]
If you add back the deleted blank lines, this is good to go.

**Review by mrstegeman — APPROVED** [review]

**Review by trentmillar — COMMENTED** [review]
added helper method as requested

**Comment by trentmillar** [comment]
> If you add back the deleted blank lines, this is good to go.

You are too fast...I noticed I reformatted after I committed and ended up chasing your correction ;)

**Comment by mrstegeman** [comment]
😄

**Pull request merged**
